-- CREATE TABLE PurchaseOrder
-- (
--     purchaseOrderID CHAR(30) NOT NULL,
--     purchaseOrderDate DATETIME NOT NULL,
--     -- customer info
--     customerFirstName VARCHAR(255) NOT NULL,
--     customerLastName VARCHAR(255) NOT NULL,
--     customerEmailAddress VARCHAR(255) NOT NULL,
--     customerPhoneNumber VARCHAR(255) NOT NULL,
--     -- address info
--     addressStreet VARCHAR(255) NOT NULL,
--     addressUnit VARCHAR(255) DEFAULT NULL,
--     addressCity VARCHAR(255) NOT NULL,
--     addressProvince CHAR(2) NOT NULL,
--     addressPostalCode CHAR(6) NOT NULL,
--     addressCountry VARCHAR(255) NOT NULL,
--     -- credit card info
--     creditCardName VARCHAR(255) NOT NULL,
--     creditCardNumber CHAR(19) NOT NULL,
--     creditCardType CHAR(64) NOT NULL,
--     creditCardExpiryDate CHAR(4) NOT NULL,
--     creditCardSecurityCode CHAR(4) NOT NULL,
--     -- purchase info
--     purchaseOrderID CHAR(30) NOT NULL,
--     purchaseOrder CHAR(30) NOT NULL,
--     postName VARCHAR(255) NOT NULL,
--     postDesc VARCHAR(255) NOT NULL,
--     postImageExt VARCHAR(4),
--     datePosted DATETIME NOT NULL,
--     PRIMARY KEY (purchaseOrderID)
-- );

-- CREATE TABLE PurchaseOrderItem
-- (
--     productID CHAR(30) NOT NULL UNIQUE,
--     purchaseOrderID CHAR(30) NOT NULL,
--     purchaseOrderItemID CHAR(30) NOT NULL,
--     purchaseOrderItemQuantity SMALLINT
--     UNSIGNED NOT NULL DEFAULT 1,
--     PRIMARY KEY
--     (purchaseOrderItemID),
--     FOREIGN KEY
--     (purchaseOrderID)
--         REFERENCES PurchaseOrder
--     (purchaseOrderID)
--         ON
--     DELETE CASCADE
--         ON
--     UPDATE CASCADE,
--     FOREIGN KEY (productID)
--         REFERENCES Product (productID)
--     ON
--     DELETE CASCADE
--         ON
--     UPDATE CASCADE
-- );